import { useEffect, useState } from 'react';
import { CalendarCheck } from 'lucide-react';
import { api } from '../lib/api';
import { hasActionPermission } from '../components/Layout';
import { useToast } from '../components/Toast';
import { useConfirm } from '../components/ConfirmDialog';
const money = (value: any) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function Closings() {
  const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ start: today, end: today, locationId: '', notes: '' }); const [locations, setLocations] = useState<any[]>([]); const [preview, setPreview] = useState<any>(null); const [rows, setRows] = useState<any[]>([]); const { showToast } = useToast(); const { confirm } = useConfirm(); const canCreate = hasActionPermission('closing:create'); const canApprove = hasActionPermission('closing:approve');
  const load = () => api.getClosings().then(setRows); useEffect(() => { load(); api.getReferenceLocations().then(setLocations); }, []);
  const previewData = async () => { const params = new URLSearchParams({ start: form.start, end: form.end }); if (form.locationId) params.set('locationId', form.locationId); try { setPreview(await api.previewClosing(params.toString())); } catch (err: any) { showToast('error', err.message); } };
  const close = async () => { const ok = await confirm({ title: 'Fechar período', message: 'Os indicadores atuais serão registrados como fotografia permanente deste período.', confirmText: 'Gerar fechamento', type: 'info' }); if (!ok) return; try { await api.createClosing(form); setPreview(null); showToast('success', 'Fechamento gerado'); load(); } catch (err: any) { showToast('error', err.message); } };
  const approve = async (id: string) => { const ok = await confirm({ title: 'Aprovar fechamento', message: 'Confirma a revisão e aprovação deste fechamento?', confirmText: 'Aprovar', type: 'info' }); if (ok) { await api.approveClosing(id); showToast('success', 'Fechamento aprovado'); load(); } };
  return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Fechamento Operacional</h1><p className="text-sm text-surface-500">Consolidação e aprovação por período</p></div><section className="rounded-lg border bg-white p-4"><div className="grid gap-3 sm:grid-cols-3"><input type="date" value={form.start} onChange={(e) => setForm({ ...form, start: e.target.value })}/><input type="date" value={form.end} onChange={(e) => setForm({ ...form, end: e.target.value })}/><select value={form.locationId} onChange={(e) => setForm({ ...form, locationId: e.target.value })}><option value="">Todos os locais</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="mt-3 flex gap-2"><button className="btn-secondary" onClick={previewData}>Calcular prévia</button>{canCreate && preview && <button className="btn-primary" onClick={close}>Gerar fechamento</button>}</div>{preview && <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[['Vendas', `${preview.sales.count} · ${money(preview.sales.revenue)}`], ['Entradas', preview.entries.count], ['Consumos', `${preview.consumption.count} · ${money(preview.consumption.cost)}`], ['Perdas', `${preview.losses.count} · ${money(preview.losses.cost)}`], ['Transferências', preview.transfers.count]].map(([label, value]) => <div className="rounded bg-surface-50 p-3" key={label as string}><p className="text-xs text-surface-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div>}</section><div className="grid gap-3">{rows.map((row) => <div key={row.id} className="rounded-lg border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-3"><CalendarCheck size={19}/><div><p className="font-semibold">Fechamento #{row.number}</p><p className="text-xs text-surface-400">{new Date(row.periodStart).toLocaleDateString('pt-BR')} a {new Date(row.periodEnd).toLocaleDateString('pt-BR')} · {row.location?.name || 'Todos os locais'}</p></div></div><div className="text-right"><span className={row.status === 'APPROVED' ? 'text-emerald-600' : 'text-amber-600'}>{row.status === 'APPROVED' ? 'Aprovado' : 'Aguardando aprovação'}</span>{canApprove && row.status === 'CLOSED' && <button className="ml-3 text-sm text-brand-600" onClick={() => approve(row.id)}>Aprovar</button>}</div></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-surface-500"><span>Vendas: {money(row.snapshot.sales.revenue)}</span><span>Consumo: {money(row.snapshot.consumption.cost)}</span><span>Perdas: {money(row.snapshot.losses.cost)}</span></div></div>)}</div></div>;
}
