import { useEffect, useState } from 'react';
import { KeyRound, Laptop, LogOut } from 'lucide-react';
import { api } from '../lib/api';
import { useToast } from '../components/Toast';

export default function Security() {
  const [sessions, setSessions] = useState<any[]>([]); const [form, setForm] = useState({ currentPassword: '', newPassword: '', confirmation: '' }); const [saving, setSaving] = useState(false); const { showToast } = useToast();
  const load = () => api.getSessions().then(setSessions).catch((err: any) => showToast('error', err.message)); useEffect(() => { load(); }, []);
  const save = async () => { if (form.newPassword !== form.confirmation) return showToast('warning', 'A confirmação da senha não confere'); try { setSaving(true); await api.changePassword({ currentPassword: form.currentPassword, newPassword: form.newPassword }); const saved = localStorage.getItem('zantra_user'); if (saved) localStorage.setItem('zantra_user', JSON.stringify({ ...JSON.parse(saved), mustChangePassword: false })); setForm({ currentPassword: '', newPassword: '', confirmation: '' }); showToast('success', 'Senha alterada com sucesso'); setTimeout(() => { window.location.href = '/'; }, 500); } catch (err: any) { showToast('error', err.message); } finally { setSaving(false); } };
  const revoke = async (id: string) => { try { await api.revokeSession(id); showToast('success', 'Sessão encerrada'); load(); } catch (err: any) { showToast('error', err.message); } };
  return <div className="mx-auto max-w-4xl space-y-5"><div><h1 className="text-2xl font-semibold">Segurança da conta</h1><p className="text-sm text-surface-500">Senha e dispositivos conectados</p></div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-lg border bg-white p-5"><div className="mb-4 flex items-center gap-2"><KeyRound size={18}/><h2 className="font-semibold">Alterar senha</h2></div><div className="space-y-3"><input type="password" className="w-full" placeholder="Senha atual" value={form.currentPassword} onChange={(e) => setForm({ ...form, currentPassword: e.target.value })}/><input type="password" className="w-full" placeholder="Nova senha" value={form.newPassword} onChange={(e) => setForm({ ...form, newPassword: e.target.value })}/><input type="password" className="w-full" placeholder="Confirmar nova senha" value={form.confirmation} onChange={(e) => setForm({ ...form, confirmation: e.target.value })}/><p className="text-xs text-surface-400">Mínimo de 10 caracteres, incluindo maiúscula, minúscula e número.</p><button className="btn-primary" disabled={saving} onClick={save}>{saving ? 'Salvando...' : 'Alterar senha'}</button></div></section><section className="rounded-lg border bg-white"><div className="flex items-center gap-2 border-b p-5"><Laptop size={18}/><h2 className="font-semibold">Sessões ativas</h2></div><div className="divide-y">{sessions.map((session) => <div key={session.id} className="flex items-center gap-3 p-4"><Laptop size={17} className="text-surface-400"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{session.userAgent || 'Dispositivo não identificado'}</p><p className="text-xs text-surface-400">{session.ipAddress || 'IP não identificado'} · {new Date(session.lastUsedAt).toLocaleString('pt-BR')}</p></div><button title="Encerrar sessão" onClick={() => revoke(session.id)} className="rounded p-2 text-red-600 hover:bg-red-50"><LogOut size={16}/></button></div>)}{!sessions.length && <p className="p-6 text-center text-sm text-surface-400">Nenhuma sessão ativa</p>}</div></section></div></div>;
}
